@TournamentAPI.Api_HostAddress = https://localhost:7151

GET {{TournamentAPI.Api_HostAddress}}/api/games

###

POST {{TournamentAPI.Api_HostAddress}}/api/games
Content-Type: application/json


  {
    "id": 0,
    "title": "Matc54h ",
    
    "tournamentId": 1,
  }

###

GET {{TournamentAPI.Api_HostAddress}}/api/games/29

###

DELETE {{TournamentAPI.Api_HostAddress}}/api/games/0

###

PUT {{TournamentAPI.Api_HostAddress}}/api/games/29
Content-Type: application/json

{
  "id":29,
  "title": "Mac5 ",
 
}

###

GET {{TournamentAPI.Api_HostAddress}}/api/tournaments

###

PUT {{TournamentAPI.Api_HostAddress}}/api/tournaments/7
Content-Type: application/json

{
    "id":7,
   "title": "MO",
}

###
